// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";
import * as ServiceBook$RescriptProjectTemplate from "./ServiceBook.bs.js";

import './App.css';
;

function App(Props) {
  RescriptReactRouter.useUrl(undefined, undefined);
  return React.createElement(ServiceBook$RescriptProjectTemplate.make, {});
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
